// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package brokers

import (
	context "context"

	brokers2 "github.com/vn-fin/xpb/xpb/brokers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BrokerGatewayServiceClient is the client API for BrokerGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerGatewayServiceClient interface {
	Login(ctx context.Context, in *brokers2.LoginRequest, opts ...grpc.CallOption) (*brokers2.LoginResponse, error)
	CreateOrder(ctx context.Context, in *brokers2.CreateOrderRequest, opts ...grpc.CallOption) (*brokers2.CreateOrderResponse, error)
	CreateFutureOrder(ctx context.Context, in *brokers2.CreateFutureOrderRequest, opts ...grpc.CallOption) (*brokers2.CreateOrderResponse, error)
	GetOrderById(ctx context.Context, in *brokers2.GetOrderRequest, opts ...grpc.CallOption) (*brokers2.GetOrderResponse, error)
	GetPendingOrders(ctx context.Context, in *brokers2.GetPendingOrdersRequest, opts ...grpc.CallOption) (*brokers2.GetPendingOrdersResponse, error)
	GetListOrders(ctx context.Context, in *brokers2.GetListOrdersRequest, opts ...grpc.CallOption) (*brokers2.GetListOrdersResponse, error)
	GetOrdersBySession(ctx context.Context, in *brokers2.GetOrdersBySessionRequest, opts ...grpc.CallOption) (*brokers2.GetOrdersBySessionResponse, error)
	CancelOrder(ctx context.Context, in *brokers2.CancelOrderRequest, opts ...grpc.CallOption) (*brokers2.CancelOrderResponse, error)
	UpdateOrder(ctx context.Context, in *brokers2.UpdateOrderRequest, opts ...grpc.CallOption) (*brokers2.UpdateOrderResponse, error)
	GetPortfolio(ctx context.Context, in *brokers2.GetPortfolioRequest, opts ...grpc.CallOption) (*brokers2.GetPortfolioResponse, error)
	GetAccountBalance(ctx context.Context, in *brokers2.GetAccountBalanceRequest, opts ...grpc.CallOption) (*brokers2.GetAccountBalanceResponse, error)
}

type brokerGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerGatewayServiceClient(cc grpc.ClientConnInterface) BrokerGatewayServiceClient {
	return &brokerGatewayServiceClient{cc}
}

func (c *brokerGatewayServiceClient) Login(ctx context.Context, in *brokers2.LoginRequest, opts ...grpc.CallOption) (*brokers2.LoginResponse, error) {
	out := new(brokers2.LoginResponse)
	err := c.cc.Invoke(ctx, "/BrokerGatewayService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerGatewayServiceClient) CreateOrder(ctx context.Context, in *brokers2.CreateOrderRequest, opts ...grpc.CallOption) (*brokers2.CreateOrderResponse, error) {
	out := new(brokers2.CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/BrokerGatewayService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerGatewayServiceClient) CreateFutureOrder(ctx context.Context, in *brokers2.CreateFutureOrderRequest, opts ...grpc.CallOption) (*brokers2.CreateOrderResponse, error) {
	out := new(brokers2.CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/BrokerGatewayService/CreateFutureOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerGatewayServiceClient) GetOrderById(ctx context.Context, in *brokers2.GetOrderRequest, opts ...grpc.CallOption) (*brokers2.GetOrderResponse, error) {
	out := new(brokers2.GetOrderResponse)
	err := c.cc.Invoke(ctx, "/BrokerGatewayService/GetOrderById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerGatewayServiceClient) GetPendingOrders(ctx context.Context, in *brokers2.GetPendingOrdersRequest, opts ...grpc.CallOption) (*brokers2.GetPendingOrdersResponse, error) {
	out := new(brokers2.GetPendingOrdersResponse)
	err := c.cc.Invoke(ctx, "/BrokerGatewayService/GetPendingOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerGatewayServiceClient) GetListOrders(ctx context.Context, in *brokers2.GetListOrdersRequest, opts ...grpc.CallOption) (*brokers2.GetListOrdersResponse, error) {
	out := new(brokers2.GetListOrdersResponse)
	err := c.cc.Invoke(ctx, "/BrokerGatewayService/GetListOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerGatewayServiceClient) GetOrdersBySession(ctx context.Context, in *brokers2.GetOrdersBySessionRequest, opts ...grpc.CallOption) (*brokers2.GetOrdersBySessionResponse, error) {
	out := new(brokers2.GetOrdersBySessionResponse)
	err := c.cc.Invoke(ctx, "/BrokerGatewayService/GetOrdersBySession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerGatewayServiceClient) CancelOrder(ctx context.Context, in *brokers2.CancelOrderRequest, opts ...grpc.CallOption) (*brokers2.CancelOrderResponse, error) {
	out := new(brokers2.CancelOrderResponse)
	err := c.cc.Invoke(ctx, "/BrokerGatewayService/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerGatewayServiceClient) UpdateOrder(ctx context.Context, in *brokers2.UpdateOrderRequest, opts ...grpc.CallOption) (*brokers2.UpdateOrderResponse, error) {
	out := new(brokers2.UpdateOrderResponse)
	err := c.cc.Invoke(ctx, "/BrokerGatewayService/UpdateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerGatewayServiceClient) GetPortfolio(ctx context.Context, in *brokers2.GetPortfolioRequest, opts ...grpc.CallOption) (*brokers2.GetPortfolioResponse, error) {
	out := new(brokers2.GetPortfolioResponse)
	err := c.cc.Invoke(ctx, "/BrokerGatewayService/GetPortfolio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerGatewayServiceClient) GetAccountBalance(ctx context.Context, in *brokers2.GetAccountBalanceRequest, opts ...grpc.CallOption) (*brokers2.GetAccountBalanceResponse, error) {
	out := new(brokers2.GetAccountBalanceResponse)
	err := c.cc.Invoke(ctx, "/BrokerGatewayService/GetAccountBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerGatewayServiceServer is the server API for BrokerGatewayService service.
// All implementations must embed UnimplementedBrokerGatewayServiceServer
// for forward compatibility
type BrokerGatewayServiceServer interface {
	Login(context.Context, *brokers2.LoginRequest) (*brokers2.LoginResponse, error)
	CreateOrder(context.Context, *brokers2.CreateOrderRequest) (*brokers2.CreateOrderResponse, error)
	CreateFutureOrder(context.Context, *brokers2.CreateFutureOrderRequest) (*brokers2.CreateOrderResponse, error)
	GetOrderById(context.Context, *brokers2.GetOrderRequest) (*brokers2.GetOrderResponse, error)
	GetPendingOrders(context.Context, *brokers2.GetPendingOrdersRequest) (*brokers2.GetPendingOrdersResponse, error)
	GetListOrders(context.Context, *brokers2.GetListOrdersRequest) (*brokers2.GetListOrdersResponse, error)
	GetOrdersBySession(context.Context, *brokers2.GetOrdersBySessionRequest) (*brokers2.GetOrdersBySessionResponse, error)
	CancelOrder(context.Context, *brokers2.CancelOrderRequest) (*brokers2.CancelOrderResponse, error)
	UpdateOrder(context.Context, *brokers2.UpdateOrderRequest) (*brokers2.UpdateOrderResponse, error)
	GetPortfolio(context.Context, *brokers2.GetPortfolioRequest) (*brokers2.GetPortfolioResponse, error)
	GetAccountBalance(context.Context, *brokers2.GetAccountBalanceRequest) (*brokers2.GetAccountBalanceResponse, error)
	mustEmbedUnimplementedBrokerGatewayServiceServer()
}

// UnimplementedBrokerGatewayServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBrokerGatewayServiceServer struct {
}

func (UnimplementedBrokerGatewayServiceServer) Login(context.Context, *brokers2.LoginRequest) (*brokers2.LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedBrokerGatewayServiceServer) CreateOrder(context.Context, *brokers2.CreateOrderRequest) (*brokers2.CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedBrokerGatewayServiceServer) CreateFutureOrder(context.Context, *brokers2.CreateFutureOrderRequest) (*brokers2.CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFutureOrder not implemented")
}
func (UnimplementedBrokerGatewayServiceServer) GetOrderById(context.Context, *brokers2.GetOrderRequest) (*brokers2.GetOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderById not implemented")
}
func (UnimplementedBrokerGatewayServiceServer) GetPendingOrders(context.Context, *brokers2.GetPendingOrdersRequest) (*brokers2.GetPendingOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPendingOrders not implemented")
}
func (UnimplementedBrokerGatewayServiceServer) GetListOrders(context.Context, *brokers2.GetListOrdersRequest) (*brokers2.GetListOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListOrders not implemented")
}
func (UnimplementedBrokerGatewayServiceServer) GetOrdersBySession(context.Context, *brokers2.GetOrdersBySessionRequest) (*brokers2.GetOrdersBySessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrdersBySession not implemented")
}
func (UnimplementedBrokerGatewayServiceServer) CancelOrder(context.Context, *brokers2.CancelOrderRequest) (*brokers2.CancelOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedBrokerGatewayServiceServer) UpdateOrder(context.Context, *brokers2.UpdateOrderRequest) (*brokers2.UpdateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrder not implemented")
}
func (UnimplementedBrokerGatewayServiceServer) GetPortfolio(context.Context, *brokers2.GetPortfolioRequest) (*brokers2.GetPortfolioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortfolio not implemented")
}
func (UnimplementedBrokerGatewayServiceServer) GetAccountBalance(context.Context, *brokers2.GetAccountBalanceRequest) (*brokers2.GetAccountBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountBalance not implemented")
}
func (UnimplementedBrokerGatewayServiceServer) mustEmbedUnimplementedBrokerGatewayServiceServer() {}

// UnsafeBrokerGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerGatewayServiceServer will
// result in compilation errors.
type UnsafeBrokerGatewayServiceServer interface {
	mustEmbedUnimplementedBrokerGatewayServiceServer()
}

func RegisterBrokerGatewayServiceServer(s grpc.ServiceRegistrar, srv BrokerGatewayServiceServer) {
	s.RegisterService(&BrokerGatewayService_ServiceDesc, srv)
}

func _BrokerGatewayService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(brokers2.LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerGatewayServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerGatewayService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerGatewayServiceServer).Login(ctx, req.(*brokers2.LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerGatewayService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(brokers2.CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerGatewayServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerGatewayService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerGatewayServiceServer).CreateOrder(ctx, req.(*brokers2.CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerGatewayService_CreateFutureOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(brokers2.CreateFutureOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerGatewayServiceServer).CreateFutureOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerGatewayService/CreateFutureOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerGatewayServiceServer).CreateFutureOrder(ctx, req.(*brokers2.CreateFutureOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerGatewayService_GetOrderById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(brokers2.GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerGatewayServiceServer).GetOrderById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerGatewayService/GetOrderById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerGatewayServiceServer).GetOrderById(ctx, req.(*brokers2.GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerGatewayService_GetPendingOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(brokers2.GetPendingOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerGatewayServiceServer).GetPendingOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerGatewayService/GetPendingOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerGatewayServiceServer).GetPendingOrders(ctx, req.(*brokers2.GetPendingOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerGatewayService_GetListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(brokers2.GetListOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerGatewayServiceServer).GetListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerGatewayService/GetListOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerGatewayServiceServer).GetListOrders(ctx, req.(*brokers2.GetListOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerGatewayService_GetOrdersBySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(brokers2.GetOrdersBySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerGatewayServiceServer).GetOrdersBySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerGatewayService/GetOrdersBySession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerGatewayServiceServer).GetOrdersBySession(ctx, req.(*brokers2.GetOrdersBySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerGatewayService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(brokers2.CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerGatewayServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerGatewayService/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerGatewayServiceServer).CancelOrder(ctx, req.(*brokers2.CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerGatewayService_UpdateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(brokers2.UpdateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerGatewayServiceServer).UpdateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerGatewayService/UpdateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerGatewayServiceServer).UpdateOrder(ctx, req.(*brokers2.UpdateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerGatewayService_GetPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(brokers2.GetPortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerGatewayServiceServer).GetPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerGatewayService/GetPortfolio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerGatewayServiceServer).GetPortfolio(ctx, req.(*brokers2.GetPortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerGatewayService_GetAccountBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(brokers2.GetAccountBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerGatewayServiceServer).GetAccountBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerGatewayService/GetAccountBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerGatewayServiceServer).GetAccountBalance(ctx, req.(*brokers2.GetAccountBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerGatewayService_ServiceDesc is the grpc.ServiceDesc for BrokerGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BrokerGatewayService",
	HandlerType: (*BrokerGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _BrokerGatewayService_Login_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _BrokerGatewayService_CreateOrder_Handler,
		},
		{
			MethodName: "CreateFutureOrder",
			Handler:    _BrokerGatewayService_CreateFutureOrder_Handler,
		},
		{
			MethodName: "GetOrderById",
			Handler:    _BrokerGatewayService_GetOrderById_Handler,
		},
		{
			MethodName: "GetPendingOrders",
			Handler:    _BrokerGatewayService_GetPendingOrders_Handler,
		},
		{
			MethodName: "GetListOrders",
			Handler:    _BrokerGatewayService_GetListOrders_Handler,
		},
		{
			MethodName: "GetOrdersBySession",
			Handler:    _BrokerGatewayService_GetOrdersBySession_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _BrokerGatewayService_CancelOrder_Handler,
		},
		{
			MethodName: "UpdateOrder",
			Handler:    _BrokerGatewayService_UpdateOrder_Handler,
		},
		{
			MethodName: "GetPortfolio",
			Handler:    _BrokerGatewayService_GetPortfolio_Handler,
		},
		{
			MethodName: "GetAccountBalance",
			Handler:    _BrokerGatewayService_GetAccountBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "brokers.proto",
}
