# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import permission_pb2 as permission__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in permission_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PermissionServiceStub(object):
    """PermissionService provides token auth + rate-limit endpoints
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/permission.PermissionService/Ping',
                request_serializer=permission__pb2.PingRequest.SerializeToString,
                response_deserializer=permission__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GenerateTokens = channel.unary_unary(
                '/permission.PermissionService/GenerateTokens',
                request_serializer=permission__pb2.GenerateTokensRequest.SerializeToString,
                response_deserializer=permission__pb2.GenerateTokensResponse.FromString,
                _registered_method=True)
        self.RefreshAccessToken = channel.unary_unary(
                '/permission.PermissionService/RefreshAccessToken',
                request_serializer=permission__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=permission__pb2.RefreshTokenResponse.FromString,
                _registered_method=True)
        self.CheckAuthToken = channel.unary_unary(
                '/permission.PermissionService/CheckAuthToken',
                request_serializer=permission__pb2.CheckAuthRequest.SerializeToString,
                response_deserializer=permission__pb2.CheckAuthResponse.FromString,
                _registered_method=True)
        self.UpdateRateLimit = channel.unary_unary(
                '/permission.PermissionService/UpdateRateLimit',
                request_serializer=permission__pb2.UpdateRateLimitRequest.SerializeToString,
                response_deserializer=permission__pb2.UpdateRateLimitResponse.FromString,
                _registered_method=True)
        self.CheckAuthFirebaseToken = channel.unary_unary(
                '/permission.PermissionService/CheckAuthFirebaseToken',
                request_serializer=permission__pb2.CheckAuthRequest.SerializeToString,
                response_deserializer=permission__pb2.CheckAuthResponse.FromString,
                _registered_method=True)
        self.GetUserIDFromFirebase = channel.unary_unary(
                '/permission.PermissionService/GetUserIDFromFirebase',
                request_serializer=permission__pb2.CheckAuthRequest.SerializeToString,
                response_deserializer=permission__pb2.GetUserIDFromFirebaseResponse.FromString,
                _registered_method=True)
        self.GetUserIDFromToken = channel.unary_unary(
                '/permission.PermissionService/GetUserIDFromToken',
                request_serializer=permission__pb2.CheckAuthRequest.SerializeToString,
                response_deserializer=permission__pb2.GetUserIDFromTokenResponse.FromString,
                _registered_method=True)
        self.GetAudFromToken = channel.unary_unary(
                '/permission.PermissionService/GetAudFromToken',
                request_serializer=permission__pb2.CheckAuthRequest.SerializeToString,
                response_deserializer=permission__pb2.GetAudFromTokenResponse.FromString,
                _registered_method=True)


class PermissionServiceServicer(object):
    """PermissionService provides token auth + rate-limit endpoints
    """

    def Ping(self, request, context):
        """Ping route
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateTokens(self, request, context):
        """Generate access + refresh tokens
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshAccessToken(self, request, context):
        """Refresh access token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAuthToken(self, request, context):
        """Check token and rate-limit; returns allowed or not
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRateLimit(self, request, context):
        """Force-update the rate-limit with Slicing-Window algorithm
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAuthFirebaseToken(self, request, context):
        """Check auth firebase token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserIDFromFirebase(self, request, context):
        """Get user ID from Firebase token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserIDFromToken(self, request, context):
        """Get user ID from regular auth token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAudFromToken(self, request, context):
        """Get audience (aud) from token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PermissionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=permission__pb2.PingRequest.FromString,
                    response_serializer=permission__pb2.PingResponse.SerializeToString,
            ),
            'GenerateTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTokens,
                    request_deserializer=permission__pb2.GenerateTokensRequest.FromString,
                    response_serializer=permission__pb2.GenerateTokensResponse.SerializeToString,
            ),
            'RefreshAccessToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshAccessToken,
                    request_deserializer=permission__pb2.RefreshTokenRequest.FromString,
                    response_serializer=permission__pb2.RefreshTokenResponse.SerializeToString,
            ),
            'CheckAuthToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAuthToken,
                    request_deserializer=permission__pb2.CheckAuthRequest.FromString,
                    response_serializer=permission__pb2.CheckAuthResponse.SerializeToString,
            ),
            'UpdateRateLimit': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRateLimit,
                    request_deserializer=permission__pb2.UpdateRateLimitRequest.FromString,
                    response_serializer=permission__pb2.UpdateRateLimitResponse.SerializeToString,
            ),
            'CheckAuthFirebaseToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAuthFirebaseToken,
                    request_deserializer=permission__pb2.CheckAuthRequest.FromString,
                    response_serializer=permission__pb2.CheckAuthResponse.SerializeToString,
            ),
            'GetUserIDFromFirebase': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserIDFromFirebase,
                    request_deserializer=permission__pb2.CheckAuthRequest.FromString,
                    response_serializer=permission__pb2.GetUserIDFromFirebaseResponse.SerializeToString,
            ),
            'GetUserIDFromToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserIDFromToken,
                    request_deserializer=permission__pb2.CheckAuthRequest.FromString,
                    response_serializer=permission__pb2.GetUserIDFromTokenResponse.SerializeToString,
            ),
            'GetAudFromToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAudFromToken,
                    request_deserializer=permission__pb2.CheckAuthRequest.FromString,
                    response_serializer=permission__pb2.GetAudFromTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'permission.PermissionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('permission.PermissionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PermissionService(object):
    """PermissionService provides token auth + rate-limit endpoints
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permission.PermissionService/Ping',
            permission__pb2.PingRequest.SerializeToString,
            permission__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permission.PermissionService/GenerateTokens',
            permission__pb2.GenerateTokensRequest.SerializeToString,
            permission__pb2.GenerateTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshAccessToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permission.PermissionService/RefreshAccessToken',
            permission__pb2.RefreshTokenRequest.SerializeToString,
            permission__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAuthToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permission.PermissionService/CheckAuthToken',
            permission__pb2.CheckAuthRequest.SerializeToString,
            permission__pb2.CheckAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRateLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permission.PermissionService/UpdateRateLimit',
            permission__pb2.UpdateRateLimitRequest.SerializeToString,
            permission__pb2.UpdateRateLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAuthFirebaseToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permission.PermissionService/CheckAuthFirebaseToken',
            permission__pb2.CheckAuthRequest.SerializeToString,
            permission__pb2.CheckAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserIDFromFirebase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permission.PermissionService/GetUserIDFromFirebase',
            permission__pb2.CheckAuthRequest.SerializeToString,
            permission__pb2.GetUserIDFromFirebaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserIDFromToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permission.PermissionService/GetUserIDFromToken',
            permission__pb2.CheckAuthRequest.SerializeToString,
            permission__pb2.GetUserIDFromTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAudFromToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permission.PermissionService/GetAudFromToken',
            permission__pb2.CheckAuthRequest.SerializeToString,
            permission__pb2.GetAudFromTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
