// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package xpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PermissionServiceClient is the client API for PermissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermissionServiceClient interface {
	// Ping route
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Generate access + refresh tokens
	GenerateTokens(ctx context.Context, in *GenerateTokensRequest, opts ...grpc.CallOption) (*GenerateTokensResponse, error)
	// Refresh access token
	RefreshAccessToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	// Check token and rate-limit; returns allowed or not
	CheckAuthToken(ctx context.Context, in *CheckAuthRequest, opts ...grpc.CallOption) (*CheckAuthResponse, error)
	// Force-update the rate-limit with Slicing-Window algorithm
	UpdateRateLimit(ctx context.Context, in *UpdateRateLimitRequest, opts ...grpc.CallOption) (*UpdateRateLimitResponse, error)
	//Check auth firebase token
	CheckAuthFirebaseToken(ctx context.Context, in *CheckAuthRequest, opts ...grpc.CallOption) (*CheckAuthResponse, error)
	// Get user ID from Firebase token
	GetUserIDFromFirebase(ctx context.Context, in *CheckAuthRequest, opts ...grpc.CallOption) (*GetUserIDFromFirebaseResponse, error)
	// Get user ID from regular auth token
	GetUserIDFromToken(ctx context.Context, in *CheckAuthRequest, opts ...grpc.CallOption) (*GetUserIDFromTokenResponse, error)
	// Get audience (aud) from token
	GetAudFromToken(ctx context.Context, in *CheckAuthRequest, opts ...grpc.CallOption) (*GetAudFromTokenResponse, error)
}

type permissionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPermissionServiceClient(cc grpc.ClientConnInterface) PermissionServiceClient {
	return &permissionServiceClient{cc}
}

func (c *permissionServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/permission.PermissionService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) GenerateTokens(ctx context.Context, in *GenerateTokensRequest, opts ...grpc.CallOption) (*GenerateTokensResponse, error) {
	out := new(GenerateTokensResponse)
	err := c.cc.Invoke(ctx, "/permission.PermissionService/GenerateTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) RefreshAccessToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, "/permission.PermissionService/RefreshAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) CheckAuthToken(ctx context.Context, in *CheckAuthRequest, opts ...grpc.CallOption) (*CheckAuthResponse, error) {
	out := new(CheckAuthResponse)
	err := c.cc.Invoke(ctx, "/permission.PermissionService/CheckAuthToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) UpdateRateLimit(ctx context.Context, in *UpdateRateLimitRequest, opts ...grpc.CallOption) (*UpdateRateLimitResponse, error) {
	out := new(UpdateRateLimitResponse)
	err := c.cc.Invoke(ctx, "/permission.PermissionService/UpdateRateLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) CheckAuthFirebaseToken(ctx context.Context, in *CheckAuthRequest, opts ...grpc.CallOption) (*CheckAuthResponse, error) {
	out := new(CheckAuthResponse)
	err := c.cc.Invoke(ctx, "/permission.PermissionService/CheckAuthFirebaseToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) GetUserIDFromFirebase(ctx context.Context, in *CheckAuthRequest, opts ...grpc.CallOption) (*GetUserIDFromFirebaseResponse, error) {
	out := new(GetUserIDFromFirebaseResponse)
	err := c.cc.Invoke(ctx, "/permission.PermissionService/GetUserIDFromFirebase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) GetUserIDFromToken(ctx context.Context, in *CheckAuthRequest, opts ...grpc.CallOption) (*GetUserIDFromTokenResponse, error) {
	out := new(GetUserIDFromTokenResponse)
	err := c.cc.Invoke(ctx, "/permission.PermissionService/GetUserIDFromToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) GetAudFromToken(ctx context.Context, in *CheckAuthRequest, opts ...grpc.CallOption) (*GetAudFromTokenResponse, error) {
	out := new(GetAudFromTokenResponse)
	err := c.cc.Invoke(ctx, "/permission.PermissionService/GetAudFromToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionServiceServer is the server API for PermissionService service.
// All implementations must embed UnimplementedPermissionServiceServer
// for forward compatibility
type PermissionServiceServer interface {
	// Ping route
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Generate access + refresh tokens
	GenerateTokens(context.Context, *GenerateTokensRequest) (*GenerateTokensResponse, error)
	// Refresh access token
	RefreshAccessToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	// Check token and rate-limit; returns allowed or not
	CheckAuthToken(context.Context, *CheckAuthRequest) (*CheckAuthResponse, error)
	// Force-update the rate-limit with Slicing-Window algorithm
	UpdateRateLimit(context.Context, *UpdateRateLimitRequest) (*UpdateRateLimitResponse, error)
	//Check auth firebase token
	CheckAuthFirebaseToken(context.Context, *CheckAuthRequest) (*CheckAuthResponse, error)
	// Get user ID from Firebase token
	GetUserIDFromFirebase(context.Context, *CheckAuthRequest) (*GetUserIDFromFirebaseResponse, error)
	// Get user ID from regular auth token
	GetUserIDFromToken(context.Context, *CheckAuthRequest) (*GetUserIDFromTokenResponse, error)
	// Get audience (aud) from token
	GetAudFromToken(context.Context, *CheckAuthRequest) (*GetAudFromTokenResponse, error)
	mustEmbedUnimplementedPermissionServiceServer()
}

// UnimplementedPermissionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPermissionServiceServer struct {
}

func (UnimplementedPermissionServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPermissionServiceServer) GenerateTokens(context.Context, *GenerateTokensRequest) (*GenerateTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateTokens not implemented")
}
func (UnimplementedPermissionServiceServer) RefreshAccessToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshAccessToken not implemented")
}
func (UnimplementedPermissionServiceServer) CheckAuthToken(context.Context, *CheckAuthRequest) (*CheckAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAuthToken not implemented")
}
func (UnimplementedPermissionServiceServer) UpdateRateLimit(context.Context, *UpdateRateLimitRequest) (*UpdateRateLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRateLimit not implemented")
}
func (UnimplementedPermissionServiceServer) CheckAuthFirebaseToken(context.Context, *CheckAuthRequest) (*CheckAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAuthFirebaseToken not implemented")
}
func (UnimplementedPermissionServiceServer) GetUserIDFromFirebase(context.Context, *CheckAuthRequest) (*GetUserIDFromFirebaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserIDFromFirebase not implemented")
}
func (UnimplementedPermissionServiceServer) GetUserIDFromToken(context.Context, *CheckAuthRequest) (*GetUserIDFromTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserIDFromToken not implemented")
}
func (UnimplementedPermissionServiceServer) GetAudFromToken(context.Context, *CheckAuthRequest) (*GetAudFromTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudFromToken not implemented")
}
func (UnimplementedPermissionServiceServer) mustEmbedUnimplementedPermissionServiceServer() {}

// UnsafePermissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermissionServiceServer will
// result in compilation errors.
type UnsafePermissionServiceServer interface {
	mustEmbedUnimplementedPermissionServiceServer()
}

func RegisterPermissionServiceServer(s grpc.ServiceRegistrar, srv PermissionServiceServer) {
	s.RegisterService(&PermissionService_ServiceDesc, srv)
}

func _PermissionService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.PermissionService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_GenerateTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).GenerateTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.PermissionService/GenerateTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).GenerateTokens(ctx, req.(*GenerateTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_RefreshAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).RefreshAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.PermissionService/RefreshAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).RefreshAccessToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_CheckAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).CheckAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.PermissionService/CheckAuthToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).CheckAuthToken(ctx, req.(*CheckAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_UpdateRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).UpdateRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.PermissionService/UpdateRateLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).UpdateRateLimit(ctx, req.(*UpdateRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_CheckAuthFirebaseToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).CheckAuthFirebaseToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.PermissionService/CheckAuthFirebaseToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).CheckAuthFirebaseToken(ctx, req.(*CheckAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_GetUserIDFromFirebase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).GetUserIDFromFirebase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.PermissionService/GetUserIDFromFirebase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).GetUserIDFromFirebase(ctx, req.(*CheckAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_GetUserIDFromToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).GetUserIDFromToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.PermissionService/GetUserIDFromToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).GetUserIDFromToken(ctx, req.(*CheckAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_GetAudFromToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).GetAudFromToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.PermissionService/GetAudFromToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).GetAudFromToken(ctx, req.(*CheckAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PermissionService_ServiceDesc is the grpc.ServiceDesc for PermissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PermissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "permission.PermissionService",
	HandlerType: (*PermissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PermissionService_Ping_Handler,
		},
		{
			MethodName: "GenerateTokens",
			Handler:    _PermissionService_GenerateTokens_Handler,
		},
		{
			MethodName: "RefreshAccessToken",
			Handler:    _PermissionService_RefreshAccessToken_Handler,
		},
		{
			MethodName: "CheckAuthToken",
			Handler:    _PermissionService_CheckAuthToken_Handler,
		},
		{
			MethodName: "UpdateRateLimit",
			Handler:    _PermissionService_UpdateRateLimit_Handler,
		},
		{
			MethodName: "CheckAuthFirebaseToken",
			Handler:    _PermissionService_CheckAuthFirebaseToken_Handler,
		},
		{
			MethodName: "GetUserIDFromFirebase",
			Handler:    _PermissionService_GetUserIDFromFirebase_Handler,
		},
		{
			MethodName: "GetUserIDFromToken",
			Handler:    _PermissionService_GetUserIDFromToken_Handler,
		},
		{
			MethodName: "GetAudFromToken",
			Handler:    _PermissionService_GetAudFromToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "permission.proto",
}
